// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Bookstore API
 *
 * API for managing books in an online bookstore.
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/mayureshucsb2019/bookstore/go"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := openapi.NewDefaultAPIService()
	DefaultAPIController := openapi.NewDefaultAPIController(DefaultAPIService)

	router := openapi.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
