// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Bookstore API
 *
 * API for managing books in an online bookstore.
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"
	"io"
	"encoding/json"
	"os"
	"database/sql"

	openapi "github.com/mayureshucsb2019/bookstore/go"
	"github.com/mayureshucsb2019/bookstore/go/db"
)

type Config struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Host     string `json:"host"`
	Port     string `json:"port"`
	DBName   string `json:"dbname"`
}

// LoadConfig reads the configuration from a JSON file.
func loadConfig(filePath string) (Config, error) {
	var config Config
	file, err := os.Open(filePath)
	if err != nil {
		return config, err
	}
	defer file.Close()

	bytes, err := io.ReadAll(file)
	if err != nil {
		return config, err
	}

	err = json.Unmarshal(bytes, &config)
	if err != nil {
		return config, err
	}

	return config, nil
}

func main() {

	// Load configuration from file
	config, err := loadConfig("config.json")
	if err != nil {
		log.Fatalf("Error loading config: %v", err)
	}

	// Initialize DB connection
    dbConn, err := db.InitDB(db.DBConfig{
		Username: config.Username,
		Password: config.Password, 
		Host: config.Host, 
		Port: config.Port,
		DBName: config.DBName,
	})
	// InitDB(username, password, host, port, dbname string)
    if err != nil {
        log.Fatalf("Failed to connect to the database: %v", err)
    }
    defer dbConn.Close()

	// Test the connection
	if err := TestDBConnection(dbConn); err != nil {
		log.Fatalf("Failed to connect to the database: %v", err)
	}
	log.Printf("Database connection is successful")

	// Create the repository with the DB connection
	bookRepo := db.NewBookRepository(dbConn)

	log.Printf("Server started")

	DefaultAPIService := openapi.NewDefaultAPIService(bookRepo)
	DefaultAPIController := openapi.NewDefaultAPIController(DefaultAPIService)

	router := openapi.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}

// TestDBConnection tests the database connection
func TestDBConnection(db *sql.DB) error {
    if err := db.Ping(); err != nil {
        return err
    }
    return nil
}
