services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema/1-create-schemas.sql:/docker-entrypoint-initdb.d/1-create-schemas.sql
      - ./schema/2-authors.sql:/docker-entrypoint-initdb.d/2-authors.sql
      - ./schema/3-books.sql:/docker-entrypoint-initdb.d/3-books.sql
      - ./schema/4-author-book.sql:/docker-entrypoint-initdb.d/4-author-book.sql
      - ./schema/5-customers.sql:/docker-entrypoint-initdb.d/5-customers.sql
      - ./schema/6-orders.sql:/docker-entrypoint-initdb.d/6-orders.sql
      - ./schema/7-order-items.sql:/docker-entrypoint-initdb.d/7-order-items.sql
      

volumes:
  mysql_data:
