openapi: 3.0.0
info:
  description: API for managing books in an online bookstore.
  title: Bookstore API
  version: 1.0.0
servers:
- url: /
paths:
  /books:
    get:
      parameters:
      - description: The page number to retrieve. Defaults to 1 if not specified.
        explode: true
        in: query
        name: pageNumber
        required: false
        schema:
          default: 1
          type: integer
        style: form
      - description: The number of items per page. Defaults to 25 if not specified.
        explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_books_get_200_response'
          description: A JSON array of books
      summary: Get a paginated list of books
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "201":
          description: Book created successfully
      summary: Add a new book
  /books/{isbn}:
    delete:
      parameters:
      - explode: false
        in: path
        name: isbn
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Book deleted successfully
        "404":
          description: Book not found
      summary: Delete a book by ISBN
    get:
      parameters:
      - explode: false
        in: path
        name: isbn
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: A single book
        "404":
          description: Book not found
      summary: Get a specific book by ISBN
    patch:
      parameters:
      - explode: false
        in: path
        name: isbn
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "200":
          description: Book updated successfully
        "404":
          description: Book not found
      summary: Update a book by ISBN
components:
  schemas:
    Book:
      example:
        author_name: author_name
        publishing_house: publishing_house
        cost: 2.302136
        number_of_pages: 5
        isbn: isbn
        name: name
        date_of_publish: 2000-01-23
        tags:
        - tags
        - tags
      properties:
        isbn:
          type: string
        name:
          type: string
        tags:
          items:
            type: string
          type: array
        author_name:
          type: string
        date_of_publish:
          format: date
          type: string
        publishing_house:
          type: string
        number_of_pages:
          type: integer
        cost:
          format: float
          type: number
      required:
      - author_name
      - date_of_publish
      - isbn
      - name
      type: object
    _books_get_200_response:
      example:
        totalItems: 0
        books:
        - author_name: author_name
          publishing_house: publishing_house
          cost: 2.302136
          number_of_pages: 5
          isbn: isbn
          name: name
          date_of_publish: 2000-01-23
          tags:
          - tags
          - tags
        - author_name: author_name
          publishing_house: publishing_house
          cost: 2.302136
          number_of_pages: 5
          isbn: isbn
          name: name
          date_of_publish: 2000-01-23
          tags:
          - tags
          - tags
        totalPages: 6
        pageSize: 5
        currentPage: 1
      properties:
        totalItems:
          description: Total number of books available.
          type: integer
        totalPages:
          description: Total number of pages.
          type: integer
        currentPage:
          description: The current page number.
          type: integer
        pageSize:
          description: The number of items per page.
          type: integer
        books:
          items:
            $ref: '#/components/schemas/Book'
          type: array
      type: object
